# Generated by Django 4.2.5 on 2023-10-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_remove_mailing_message_mailing_clients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='periodicity',
            field=models.PositiveSmallIntegerField(choices=[('day', 'Раз в день'), ('week', 'Раз в неделю'), ('month', 'Раз в месяц')], default=1, verbose_name='Периодичность'),
        ),
    ]
