# Generated by Django 4.2.5 on 2023-10-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_clients_options_clients_creator_and_more'),
        ('mailing', '0008_alter_mailing_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='clients.clients', verbose_name='клиенты'),
        ),
    ]
