# Generated by Django 4.2.5 on 2023-10-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_logs_change_time_alter_logs_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлено'), ('failed', 'Не удалось отправить'), ('pending', 'В ожидании')], default='pending', max_length=10, verbose_name='статус попытки'),
        ),
    ]
