# Generated by Django 4.2.5 on 2023-10-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0012_remove_message_mailing_mailing_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logs',
            name='change_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата и время последней попытки'),
        ),
    ]
