# Generated by Django 4.2.5 on 2023-10-09 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clients_options_alter_clients_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={},
        ),
        migrations.AlterModelManagers(
            name='clients',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='clients',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='is_email_active',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='password',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='verify_key',
        ),
    ]
